### ISSUE TITLE
Auto-scroll to bottom

### ISSUE THREAD

**Issue by creynders** [tcarlsen/atom-message-panel#21]
Hiya,

I'm using your message panel package in my upcoming atom package, which basically consists out of running a command line tool. However, the output of the BufferedProcess stdout is rather large and when I dump it in a plainmessageview it doesn't fit into the message pane entirely. By default the message pane shows the beginning of the message, but since this is output generated from a process, it is more intuitive and user-friendly that the last line of the output is shown, since that's where the process success status is printed. Would it be feasible you think to have a 'autoscroll' property or something, which will automatically scroll the message pane to the end of the message?

I hope you understand what I'm trying to achieve here, if not please let me know!

**Comment by tcarlsen** [comment]
fixed in #61
