### ISSUE TITLE
How do I find if the MessagePanelView is shown

### ISSUE THREAD

**Issue by basarat** [tcarlsen/atom-message-panel#55]
I can `toggle` it, but I need to know its current state before I toggle.

**Comment by basarat** [comment]
Got it:

```js
// from : https://github.com/tcarlsen/atom-csslint/blob/master/lib/linter.coffee
function hide() {
    if (messagePanel.summary.css("display") !== "none") {
        messagePanel.toggle();
    }
}
function show() {
    if (messagePanel.summary.css("display") === "none") {
        messagePanel.toggle();
    }
}
```
Thanks! 
Would be great to add to core ;)

**Comment by tcarlsen** [comment]
this is on the roadmap see #23

**Comment by basarat** [comment]
Cool. Having found how to do this, I found it highly disruptive to toggle it on the user from API, so ended up not using it at all :)

**Comment by tcarlsen** [comment]
Did it at my lint package. See https://github.com/tcarlsen/atom-jslint/blob/master/lib/linter.coffee#L22

—
