### ISSUE TITLE
Clicking on line/column in LineMessageView doesn't return focus to the editor.

### ISSUE THREAD

**Issue by sbenhaim** [tcarlsen/atom-message-panel#74]
Clicking on the line and column info on a LineMessageView entry takes me to the correct location in the document, but doesn't return focus to the editor, so I need to click with the mouse to get back.

Any reason focus shouldn't jump back to the editor?

**Comment by tcarlsen** [comment]
No it should focus on editor. I'm Aware of this but haven't had time to fix
