### ISSUE TITLE
Calling `clear()` still shows contents in title when collapsed

### ISSUE THREAD

**Issue by andrewrynhard** [tcarlsen/atom-message-panel#75]
I apologize if the title is confusing. Pictures probably explain this best. With the following code, when the body is cleared and the panel is toggled up I still see old messages that should have been cleared.

````coffeescript
fs = require 'fs'
path = require 'path'
{MessagePanelView, LineMessageView, PlainMessageView} = require('atom-message-panel')

module.exports =
class MessageView

  constructor: ->
    @messagepanel = new MessagePanelView({title: 'TeXlicious: '}) unless @messagepanel?

  update: (errors) ->
    @messagepanel.clear()
    if errors == null
      @messagepanel.toggle()
      return

    for error in errors
      @messagepanel.add(new LineMessageView({file: error.file , line: error.line, character: 0, message: error.message}))

    @messagepanel.attach()

  destroy: =>
    @messagepanel?.remove()
    @messagepanel = null
````
Here is what the message panel looks like after clearing and toggling down:
<img width="726" alt="screen shot 2015-08-13 at 5 19 40 pm" src="https://cloud.githubusercontent.com/assets/3383143/9264799/88b4de22-41df-11e5-8de9-14128b89cb64.png">

Here is what the message panel looks like after clearing and toggling up:
<img width="721" alt="screen shot 2015-08-13 at 5 19 49 pm" src="https://cloud.githubusercontent.com/assets/3383143/9264800/88cd43cc-41df-11e5-8858-8c2f01ef6494.png">

**Comment by tcarlsen** [comment]
sorry for the late fix!
