### ISSUE TITLE
Taking input in panel

### ISSUE THREAD

**Issue by arrayoutofbounds** [tcarlsen/atom-message-panel#78]
Is there a way to take in input from the panel? I.e so there is a cursor at the next line and anything typed will be sent back to a callback function?

**Comment by tcarlsen** [comment]
not totally sure what you want her, but maybe take a look at https://github.com/Glavin001/atom-gitter @Glavin001 was making a chat along with AMP

AMP is only for displaying data, if you want input you need to build around AMP

**Comment by arrayoutofbounds** [comment]
i just wanted to use the atom message panel but with a cursor on the next line...so the user can enter input that the running programs needs (like the console in eclipse that lets you input if the program is asking for input). Thank you! I love the message panel.

**Comment by tcarlsen** [comment]
I believe you need to make the input (next line cursor) yourself by adding it to the AMP panel like:

```coffeescript
messages = new MessagePanelView
      title: 'TEST'

messages.append('<input id="input-msg">')
