### ISSUE TITLE
I believe that the missing clipboard functionality of "script" plugin needs to be fixed here.

### ISSUE THREAD

**Issue by oderwat** [tcarlsen/atom-message-panel#79]
Please see this issue: https://github.com/rgbkrk/atom-script/issues/642

Mac Users seem to have a problem with the clipboard copy/paste functionality. As I believe that the current Script version uses atom-message-panel I think that problem could originate from here.

Ideas?

**Comment by derwentx** [comment]
I'd like to fix this problem, however I'm a bit of a GitHub noob, so this may sound like a strange question: if I dive into the JS and attempt to fix this problem, and create a merge request, is this repo active enough that it would be looked at? it looks like nothing has been looked at in a year. Cheers.

**Comment by tcarlsen** [comment]
I understand the question. And yes its pretty inactive. If its a fix I will look at it. but new features will not be added

**Comment by tcarlsen** [comment]
@derwentx are you still on this?

**Comment by tcarlsen** [comment]
I would love to see a PR, but for now I close this issue

**Comment by derwentx** [comment]
Probably won't ever get around to it, sorry!
