### ISSUE TITLE
fixed height of message panel ?

### ISSUE THREAD

**Issue by skywind3000** [tcarlsen/atom-message-panel#80]
Just like output panel in visual studio
Can message panel have an option to disable automatic height growth ? and leave an default-height in this new mode ? 
Please let me resize it by dragging the message panel border up and down.
auto growth is very annoy for many people.

I have tried a lot to modify source code of atom-message-panel to achieve this, but I failed.
Fortunately, I find here

**Comment by Dowwie** [comment]
+1  I would also like this feature but am without the skills to make it so

**Comment by tcarlsen** [comment]
You have the `maxHeight ` property?  

From README: *maxHeight: set a max-height of the panel body (default is 170px)*

drag to resize should also work in the latest version?

**Comment by skywind3000** [comment]
I have already set the maxHeight to 300, if I don't do this, the height of atom-message-panel will continue growing until occupy the whole atom workspace.

But if I do set it to 300, I can't drag it to resize a litter higher.

**Comment by skywind3000** [comment]
Atom-message-panel is a nice widget, but it's still no so perfect, especially the behavior of automatical growth and the maxHeight behavior.

Can I have something like the output panel in NotePad++ or Visual Studio ?

**Comment by tcarlsen** [comment]
so the solution is: even though you have set maxheight the user should be able to surpass that by dragging?

**Comment by tcarlsen** [comment]
fixed in PR #85 

release will follow soon!

**Comment by tcarlsen** [comment]
`1.3.0` is out and live on npm
