### ISSUE TITLE
Message panel won't open again after being closed

### ISSUE THREAD

**Issue by pensierinmusica** [tcarlsen/atom-message-panel#92]
@tcarlsen any chance to see this fixed?

https://github.com/rgbkrk/atom-script/issues/2006#issuecomment-573624757

Thx!

**Comment by tcarlsen** [comment]
If you make a pr I gladly look at it... atm I dont have the time to fix it myself

**Comment by pensierinmusica** [comment]
@tcarlsen it's unclear to me if the problem comes from the `atom-script` or the `atom-message-panel` module.

But since there's already a PR in `atom-script` that should fix this problem (https://github.com/rgbkrk/atom-script/pull/2004) I would close this issue here for now if you agree.

**Comment by tcarlsen** [comment]
👍
